# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Open World Object Discovery
short_description: Object Discovery Challenge focusing on novel object discovery
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.png
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: View the leaderboard here.
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2022-05-10 00:00:00
end_date: 2022-06-20 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ['unknown_auc', 'unknown_cum_pur', 'unknown_cum_cov', 'unknown_num_obj', 'number_of_clusters',
                   ],
        "default_order_by": 'unknown_auc',
      }



challenge_phases:
  - id: 1
    name: Dev Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2022-05-10 00:00:00
    end_date: 2022-06-20 23:59:59
    test_annotation_file: annotations/test_annotation.zip
    codename: dev
    max_submissions_per_day: 99
    max_submissions_per_month: 99
    max_submissions: 99
    submission_meta_attributes:
      - name: Method name
        description: give your method a cool name
        type: text
        is_visible: True
        required: True
      - name: Did you use external data?
        description: No, or a description of the external data
        type: text
        required: True
      - name: Pretraining
        description: No, or a description of the pretraining method
        type: text
        required: True
    default_submission_meta_attributes:
      - name: method_name
        is_visible: False
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".zip"

dataset_splits:
  - id: 1
    name: Validation set 0.4_1
    codename: val_split
  - id: 2
    name: Test set
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 4
    is_leaderboard_order_descending: True
